// lex.js
// Sauerkraut Lexikon
var SauerkrautLex = exports = module.exports = (function(){

  return {
    
    tags: {
      '@font-face': '@schrift-gesicht'
    , 'h1': 'ü1'
    , 'h2': 'ü2'
    , 'h3': 'ü3'
    , 'h4': 'ü4'
    , 'h5': 'ü5'
    , 'h6': 'ü6'
    , 'body': 'körper'
    , 'article': 'artikel'
    , 'abbr': 'abkürzung'
    , 'acronym': 'akronym'
    , 'address': 'adresse'
    , 'area': 'bereich'
    , 'strong': 'stark'
    , 'base': 'basis'
    , 'big': 'groß'
    , 'small': 'klein'
    , 'button': 'knopf'
    , 'div': 'box'
    , 'em': 'betont'
    , 'fieldset': 'feldset'
    , 'img': 'bild'
    , 'label': 'bezeichner'
    , 'legend': 'legende'
    , 'input': 'eingabe'
    , 'select': 'auswahl'
    , 'span': 'text'
    , 'table': 'tabelle'
    , 'ul': 'liste'
    , 'li': 'listenelement'
    , 'a': 'anker'
    , 'b': 'fett'
    , 'i': 'schief'
    , 'u': 'unterstrichen'
    , 'p': 'absatz'
    }

  , pseudos: {
      'first-child': 'erstes-kind'
    , 'not': 'nicht'
  }

  , properties: {
      'azimuth' : 'azimuth <- ####### edit'
    , 'background': 'hintergrund'
    , 'background-attachment': 'background-attachment <- ####### edit'
    , 'background-color': 'hintergrund-farbe'
    , 'background-image': 'hintergrund-bild'
    , 'background-position': 'hintergrund-position'
    , 'background-repeat': 'hintergrund-wiederholung'
    , 'border': 'rand'
    , 'border-collapse' : 'rand-kollabs <- ####### edit'
    , 'border-color' : 'rand-farbe'
    , 'border-spacing' : 'rand-abstand'
    , 'border-style' : 'rand-stil'
    , 'border-top' : 'rand-oben'
    , 'border-right' : 'rand-rechts'
    , 'border-bottom' : 'rand-unten'
    , 'border-left' : 'rand-links'
    , 'border-top-color' : 'rand-oben-farbe'
    , 'border-right-color' : 'rand-rechts-farbe'
    , 'border-bottom-color' : 'rand-unten-farbe'
    , 'border-left-color' : 'rand-links-farbe'
    , 'border-top-style' : 'rand-oben-stil'
    , 'border-right-style' : 'rand-rechts-stil'
    , 'border-bottom-style' : 'rand-unten-stil'
    , 'border-left-style' : 'rand-links-stil'
    , 'border-top-width' : 'rand-oben-breite'
    , 'border-right-width' : 'rand-rechts-breite'
    , 'border-bottom-width' : 'rand-unten-breite'
    , 'border-left-width' : 'rand-links-breite'
    , 'border-width' : 'rand-breite'
    , 'bottom' : 'unten'
    , 'caption-side' : 'caption-side <- ####### edit'
    , 'clear' : 'säubern'
    , 'clip' : 'clip <- ####### edit'
    , 'color' : 'farbe'
    , 'content' : 'inhalt'
    , 'counter-increment' : 'counter-increment <- ####### edit'
    , 'counter-reset' : 'counter-reset <- ####### edit'
    , 'cue' : 'cue  <- ####### edit'
    , 'cue-after' : 'cue-after <- ####### edit'
    , 'cue-before' : 'cue-before <- ####### edit'
    , 'cursor' : 'zeiger'
    , 'direction' : 'ausrichtung'
    , 'display' : 'ausrichtung'
    , 'elevation' : 'ausrichtung'
    , 'empty-cells' : 'ausrichtung'
    , 'float' : 'ausrichtung'
    , 'font' : 'ausrichtung'
    , 'font-family' : 'ausrichtung'
    , 'font-size' : 'ausrichtung'
    , 'font-size-adjust' : 'ausrichtung'
    , 'font-stretch' : 'ausrichtung'
    , 'font-style' : 'ausrichtung'
    , 'font-variant' : 'ausrichtung'
    , 'font-weight' : 'ausrichtung'
    , 'height' : 'ausrichtung'
    , 'left' : 'ausrichtung'
    , 'letter-spacing' : 'ausrichtung'
    , 'line-height' : 'ausrichtung'
    , 'list-style' : 'ausrichtung'
    , 'list-style-image' : 'ausrichtung'
    , 'list-style-position' : 'ausrichtung'
    , 'list-style-type' : 'ausrichtung'
    , 'margin' : 'ausrichtung'
    , 'margin-top' : 'ausrichtung'
    , 'margin-right' : 'ausrichtung'
    , 'margin-bottom' : 'ausrichtung'
    , 'margin-left' : 'ausrichtung'
    , 'margin-bottom' : 'ausrichtung'
    , 'marker-offset' : 'ausrichtung'
    , 'marks' : 'ausrichtung'
    , 'max-height' : 'ausrichtung'
    , 'max-width' : 'ausrichtung'
    , 'min-height' : 'ausrichtung'
    , 'min-width' : 'ausrichtung'
    , 'orphans' : 'ausrichtung'
    , 'outline' : 'ausrichtung'
    , 'outline-color' : 'ausrichtung'
    , 'outline-style' : 'ausrichtung'
    , 'outline-width' : 'ausrichtung'
    , 'overflow' : 'ausrichtung'
    , 'padding' : 'ausrichtung'
    , 'padding-top' : 'ausrichtung'
    , 'padding-right' : 'ausrichtung'
    , 'padding-bottom' : 'ausrichtung'
    , 'padding-left' : 'ausrichtung'
    , 'page' : 'ausrichtung'
    , 'page-break-after' : 'ausrichtung'
    , 'page-break-before' : 'ausrichtung'
    , 'page-break-inside' : 'ausrichtung'
    , 'pause' : 'ausrichtung'
    , 'pause-after' : 'ausrichtung'
    , 'pause-before' : 'ausrichtung'
    , 'pitch' : 'ausrichtung'
    , 'pitch-range' : 'ausrichtung'
    , 'play-during' : 'ausrichtung'
    , 'position' : 'ausrichtung'
    , 'quotes' : 'ausrichtung'
    , 'richness' : 'ausrichtung'
    , 'right' : 'ausrichtung'
    , 'size' : 'ausrichtung'
    , 'speak' : 'ausrichtung'
    , 'speak-header' : 'ausrichtung'
    , 'speak-numeral' : 'ausrichtung'
    , 'speak-punctuation' : 'ausrichtung'
    , 'speech-rate' : 'ausrichtung'
    , 'stress' : 'ausrichtung'
    , 'table-layout' : 'ausrichtung'
    , 'text-align' : 'ausrichtung'
    , 'text-decoration' : 'ausrichtung'
    , 'text-indent' : 'ausrichtung'
    , 'text-shadow' : 'ausrichtung'
    , 'text-transform' : 'ausrichtung'
    , 'top' : 'ausrichtung'
    , 'unicode-bidi' : 'ausrichtung'
    , 'vertical-align' : 'ausrichtung'
    , 'visibility' : 'ausrichtung'
    , 'voice-family' : 'ausrichtung'
    , 'volume' : 'ausrichtung'
    , 'white-space' : 'ausrichtung'
    , 'widows' : 'ausrichtung'
    , 'width' : 'ausrichtung'
    , 'word-spacing' : 'ausrichtung'
    , 'z-index' : 'ausrichtung'
    , 'transition' : 'übergang'
    }

  , values: {

    }
  };

})();